# Generated by Django 3.1.5 on 2021-01-22 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('bill_number', models.CharField(max_length=255)),
                ('bill_image', models.ImageField(upload_to='bill/')),
                ('date', models.DateField(auto_now_add=True)),
                ('item_brand_name', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.item')),
                ('rack_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.rack')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.vendordetail')),
            ],
        ),
    ]
