# Generated by Django 3.1.5 on 2021-01-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rack_stockdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetail',
            name='bill_image',
            field=models.ImageField(null=True, upload_to='bill/'),
        ),
    ]
