# Generated by Django 3.1.5 on 2021-01-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20210123_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockdetail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendordetail',
            name='user',
        ),
    ]
